### ISSUE TITLE
Open Source Review

### ISSUE THREAD

**Issue by jorgeborges** [theiconic/docker-nginx-akeneo#5]
1. In the Dockerfile, can you put the engineering team instead of yourself?
`MAINTAINER` THE ICONIC ENGINEERING TEAM <engineering@theiconic.com.au>`

2. I think having a nice title instead of docker-nginx-akeneo would be better

3. Add a Contributors section in the README, check out https://github.com/theiconic/php-ga-measurement-protocol for an example

4. Add a LICENSE file and License section in the README, check out https://github.com/theiconic/php-ga-measurement-protocol for an example

5. Upload a Docker image to the THE ICONIC Docker Hub account, so that people using only has to Pull the image and not build it. Dockerhub will also automatically build your container (CI) when there is a change in the repo, so you'll know when something broke. https://hub.docker.com/u/theiconic/dashboard/

**Comment by ashon-ikon** [comment]
Thanks @jorgeborges . All issues addressed as recommended.
